FROM golang:1.19-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./internal/cmd/receiver/main.go


FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app/main /main

CMD ["/main"]