version: '3.7'

services:
  db:
    container_name: DB
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
