name: Deploy Develop Backend

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME_RECEIVER }}
  PORT: ${{ secrets.PORT }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEVELOP }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: ${{ secrets.REPOSITORY_HOST }}/${{ secrets.GCP_PROJECT_ID_DEVELOP }}/${{ secrets.GCP_IMAGE_REPOSITORY_ID_DEVELOP }}/${{ secrets.SERVICE_NAME_RECEIVER }}:${{ github.sha }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID_DEVELOP }}
          service_account_key: ${{ secrets.GCP_SA_KEY_DEVELOP }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker ${{ secrets.REPOSITORY_HOST }} --quiet

      - name: Build a docker image
        run: docker build -f Dockerfile.receiver -t $IMAGE . --platform=linux/amd64


      - name: Push the docker image to Container Registry
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --project $GCP_PROJECT_ID \
            --region $GCP_REGION \
            --platform=managed \
            --quiet